name: Grading Workflow

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Use a recent Python 3 version

    - name: Download latest test files
      run: |
        # Create the target directory if it doesn't exist
        mkdir -p .github/tests
        curl -o .github/tests/requirements.txt https://raw.githubusercontent.com/UCSF-DataSci/datasci223-assignment3/main/.github/tests/requirements.txt
        curl -o .github/tests/test_assignment.py https://raw.githubusercontent.com/UCSF-DataSci/datasci223-assignment3/main/.github/tests/test_assignment.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/tests/requirements.txt

    - name: Setup Jupyter Kernel
      run: |
        pip install ipykernel
        python -m ipykernel install --user --name=python3 --display-name="Python 3"

    - name: Execute notebook
      run: |
        papermill MYSTERY.ipynb executed_notebook.ipynb -k python3
      # Continue even if the notebook fails, as the test might still pass or provide useful info
      continue-on-error: true

    - name: Run tests
      run: |
        pytest .github/tests/test_assignment.py
